name: CMake Build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++

      - name: Configure CMake
        run: |
          mkdir build
          cd build 
          cmake ..
      
      - name: Build project
        run: |
          cd build
          make
      
      - name: Release executable
        uses: actions/upload-artifact@v3
        with:
          name: Linux build
          path: build/HashMap


# jobs:
#   build:
#     run-on: windows-latest

#     steps: