name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux-build: 
    name: linux-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++

      - name: Configure CMake
        run: |
          mkdir build
          cd build 
          cmake ..
      
      - name: Build project
        run: |
          cd build
          make
      
      - name: Release executable
        uses: actions/upload-artifact@v4
        with:
          name: Linux build
          path: build/HashMap


  windows-build: 
    name: windows-build
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        uses: msys2/setup-msys2@v2
        with:
          install: make cmake mingw-w64-x86_64-gcc

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G "MinGw Makefiles" ..
          mingw32-make

      - name: Release executable
        uses: actions/upload-artifact@v4
        with:
          name: Windows build
          path: build/HashMap.exe

      # - name: Install CMake and MSYS2
      #   run: |
      #     choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      #     choco install msys2
      #     refreshenv
      
      # - name: Setup MSYS
      #   run: |
      #     C:\msys64\usr\bin\bash.exe -c "pacman -Sy --noconfirm"
      #     C:\msys64\usr\bin\bash.exe -c "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make"

